
    create table chamados (
       id int4 generated by default as identity,
        data_abertura date,
        data_fechamento date,
        observacoes varchar(255),
        prioridade int4,
        status int4,
        titulo varchar(255),
        cliente_id int4,
        tecnico_id int4,
        primary key (id)
    );

    create table perfis (
       pessoas_id int4 not null,
        perfis int4
    );

    create table pessoas (
       dtype varchar(31) not null,
        id int4 generated by default as identity,
        cpf varchar(255),
        data_criacao date,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    alter table if exists pessoas 
       add constraint UK_c7pqbmo6e96slvonilywsb8oe unique (cpf);

    alter table if exists pessoas 
       add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);

    alter table if exists chamados 
       add constraint FKbco278opsmt208i3soj8gdcuf 
       foreign key (cliente_id) 
       references pessoas;

    alter table if exists chamados 
       add constraint FK8bjv37p24o05tq03f5t4h3hgl 
       foreign key (tecnico_id) 
       references pessoas;

    alter table if exists perfis 
       add constraint FKj5ugpoh34vx9sk3xpxo0umyrg 
       foreign key (pessoas_id) 
       references pessoas;

    create table chamados (
       id  serial not null,
        data_abertura date,
        data_fechamento date,
        observacoes varchar(255),
        prioridade int4,
        status int4,
        titulo varchar(255),
        cliente_id int4,
        tecnico_id int4,
        primary key (id)
    );

    create table perfis (
       pessoas_id int4 not null,
        perfis int4
    );

    create table pessoas (
       dtype varchar(31) not null,
        id  serial not null,
        cpf varchar(255),
        data_criacao date,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    alter table pessoas 
       add constraint UK_c7pqbmo6e96slvonilywsb8oe unique (cpf);

    alter table pessoas 
       add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);

    alter table chamados 
       add constraint FKbco278opsmt208i3soj8gdcuf 
       foreign key (cliente_id) 
       references pessoas;

    alter table chamados 
       add constraint FK8bjv37p24o05tq03f5t4h3hgl 
       foreign key (tecnico_id) 
       references pessoas;

    alter table perfis 
       add constraint FKj5ugpoh34vx9sk3xpxo0umyrg 
       foreign key (pessoas_id) 
       references pessoas;

    create table chamados (
       id int4 generated by default as identity,
        data_abertura date,
        data_fechamento date,
        observacoes varchar(255),
        prioridade int4,
        status int4,
        titulo varchar(255),
        cliente_id int4,
        tecnico_id int4,
        primary key (id)
    );

    create table perfis (
       pessoas_id int4 not null,
        perfis int4
    );

    create table pessoas (
       dtype varchar(31) not null,
        id int4 generated by default as identity,
        cpf varchar(255),
        data_criacao date,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    alter table if exists pessoas 
       add constraint UK_c7pqbmo6e96slvonilywsb8oe unique (cpf);

    alter table if exists pessoas 
       add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);

    alter table if exists chamados 
       add constraint FKbco278opsmt208i3soj8gdcuf 
       foreign key (cliente_id) 
       references pessoas;

    alter table if exists chamados 
       add constraint FK8bjv37p24o05tq03f5t4h3hgl 
       foreign key (tecnico_id) 
       references pessoas;

    alter table if exists perfis 
       add constraint FKj5ugpoh34vx9sk3xpxo0umyrg 
       foreign key (pessoas_id) 
       references pessoas;
